"""
AutoHeal AI - AutoHeal Agent API Schemas
==========================================
"""

from datetime import datetime
from typing import Optional, Any
from pydantic import BaseModel, Field
from enum import Enum


class HealingStatus(str, Enum):
    """Status of a healing operation."""
    PENDING = "pending"
    OBSERVING = "observing"
    ORIENTING = "orienting"
    DECIDING = "deciding"
    ACTING = "acting"
    VALIDATING = "validating"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class ActionType(str, Enum):
    """Types of healing actions."""
    RESTART_POD = "restart_pod"
    SCALE_UP = "scale_up"
    SCALE_DOWN = "scale_down"
    ROLLBACK = "rollback"
    INCREASE_RESOURCES = "increase_resources"
    CIRCUIT_BREAKER = "circuit_breaker"
    RATE_LIMIT = "rate_limit"
    FAILOVER = "failover"
    CUSTOM = "custom"


class HealingRequest(BaseModel):
    """Request to heal an incident."""
    
    incident_id: str = Field(..., description="Incident to heal")
    target_service: str = Field(..., description="Service to heal")
    target_namespace: str = Field(default="default")
    severity: str = Field(default="medium")
    root_cause: Optional[str] = None
    recommended_actions: list[str] = Field(default_factory=list)
    force: bool = Field(default=False)


class HealingAction(BaseModel):
    """A single healing action."""
    
    action_id: str = Field(...)
    action_type: ActionType = Field(...)
    target: str = Field(..., description="Target resource")
    parameters: dict[str, Any] = Field(default_factory=dict)
    reasoning: str = Field(..., description="Why this action was chosen")
    risk_level: str = Field(default="low")
    reversible: bool = Field(default=True)


class HealingPlan(BaseModel):
    """A complete healing plan generated by OODA."""
    
    plan_id: str = Field(...)
    incident_id: str = Field(...)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    # OODA phases
    observation: str = Field(..., description="What was observed")
    orientation: str = Field(..., description="Analysis and context")
    decision: str = Field(..., description="Chosen approach")
    
    # Actions
    actions: list[HealingAction] = Field(...)
    estimated_duration_seconds: int = Field(default=60)
    
    # Confidence
    confidence: float = Field(ge=0, le=1)
    risk_assessment: str = Field(...)


class HealingResult(BaseModel):
    """Result of a healing operation."""
    
    healing_id: str = Field(...)
    incident_id: str = Field(...)
    status: HealingStatus = Field(...)
    
    plan: Optional[HealingPlan] = None
    
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    
    actions_executed: int = Field(default=0)
    actions_successful: int = Field(default=0)
    
    result_message: Optional[str] = None
    error_message: Optional[str] = None


class OODAState(BaseModel):
    """Current state of an OODA loop."""
    
    healing_id: str = Field(...)
    phase: str = Field(...)
    observation: Optional[str] = None
    orientation: Optional[str] = None
    decision: Optional[str] = None
    actions: list[dict] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=datetime.utcnow)
